server:
  listen_addr: "${TAUTH_LISTEN_ADDR}"
  database_url: "${TAUTH_DATABASE_URL}"
  enable_cors: "${TAUTH_ENABLE_CORS}"
  cors_allowed_origins:
    - ${TAUTH_CORS_ORIGIN_1}
  cors_allowed_origin_exceptions:
    - "${TAUTH_CORS_EXCEPTION_1}"
  enable_tenant_header_override: ${TAUTH_ENABLE_TENANT_HEADER_OVERRIDE}

tenants:
  - id: ${TAUTH_TENANT_ID_PINGUIN}
    display_name: ${TAUTH_TENANT_DISPLAY_NAME_PINGUIN}
    tenant_origins:
      - ${TAUTH_CORS_ORIGIN_1}
    google_web_client_id: "${TAUTH_TENANT_GOOGLE_WEB_CLIENT_ID_PINGUIN}"
    jwt_signing_key: "${TAUTH_TENANT_JWT_SIGNING_KEY_PINGUIN}"
    cookie_domain: "${TAUTH_COOKIE_DOMAIN}"
    session_cookie_name: ${TAUTH_TENANT_SESSION_COOKIE_NAME_PINGUIN}
    refresh_cookie_name: ${TAUTH_TENANT_REFRESH_COOKIE_NAME_PINGUIN}
    session_ttl: "30m"
    refresh_ttl: "720h"
    nonce_ttl: "5m"
    allow_insecure_http: "${TAUTH_ALLOW_INSECURE_HTTP}"
    allowed_users:
    
